name: Build and push the Image on Azure container Registry

on:
  push:
    branches:
      [ main ]
  workflow_dispatch:  # Allows manual triggering of the workflow and passing of inputs from the GitHub UI 
        # you can define inputs here if needed
    
#    paths:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.POC_CICD_AKS_CRED }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/hotstar-poc:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/hotstar-poc:${{ github.sha }}

      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository using HTTPS URL without token
          git clone https://github.com/dixitrathi7/GitOps_K8s_manifest.git gitops

          cd gitops/hotstar_clone_manifest
          
          sed -i "s|image: .*|image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/hotstar-poc:${{ github.sha }}|g" deployment.yml
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yml
          git commit -m "Update image to ${{ github.sha }}"
          
          # Push
          git push -f https://${GIT_TOKEN}@github.com/dixitrathi7/GitOps_K8s_manifest.git main
