name: Build and push the Image on Azure container Registry

on:
  push:
    branches:
      [ main ]
  workflow_dispatch:  # Allows manual triggering of the workflow and passing of inputs from the GitHub UI 
        # you can define inputs here if needed
    
#    paths:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.POC_CICD_AKS_CRED }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/hotstar-poc:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/hotstar-poc:${{ github.sha }}
